AWSTemplateFormatVersion: 2010-09-09
Description: 'Miztiik Automation: This template creates an EC2 instance. Your task to update it, so that the template can tag root volume of the EC2 Instance'
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to SSH to the EC2 instances.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t2.micro, t2.small]
    ConstraintDescription: Please choose a valid instance type.
  InstanceAZ:
   Description: EC2 AZ.
   Type: AWS::EC2::AvailabilityZone::Name
   ConstraintDescription: "Must be the name of an availabity zone."
  MiztiikCustomAMI:
    Type : AWS::SSM::Parameter::Value<String>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:
  #Tagging the root volume for the EC2 instances with the Windows OS
  #The commented out powershell commands are to utilize if the AMI has the AWS CLI installed and you prefer that approach.
  #Tagging the root volume for EC2 instances with an Unix OS with the AWS CLI installed.
  MystikalInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref MiztiikCustomAMI
      InstanceType: !Ref InstanceType
      AvailabilityZone: !Ref InstanceAZ
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          AWS_AVAIL_ZONE=$(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)
          AWS_REGION="`echo \"$AWS_AVAIL_ZONE\" | sed 's/[a-z]$//'`"
          AWS_INSTANCE_ID=$(curl http://169.254.169.254/latest/meta-data/instance-id)
          ROOT_VOLUME_IDS=$(aws ec2 describe-instances --region $AWS_REGION --instance-id $AWS_INSTANCE_ID --output text --query Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId)
          aws ec2 create-tags --resources $ROOT_VOLUME_IDS --region $AWS_REGION --tags Key=MiztiikAutomation,Value=RootVolumeTagged
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
        - 
          Key: Application
          Value: Miztiik-Automation
        - 
          Key: GithubRepo
          Value: "https://github.com/miztiik/cfn-challenges"
        - 
          Key: LearnCdk
          Value: ""
        - 
          Key: Owner
          Value: Mystique
        - 
          Key: OwnerProfile
          Value: "https://github.com/miztiik"
        - 
          Key: ToKnowMore
          Value: "https://youtube.com/c/valaxytechnologies"

      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: '200'
            DeleteOnTermination: 'true'
            VolumeSize: '10'

  #AMI role given to the instances, the instances need the describe and create tags to complete the UserData
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: MystiqueAutomationTagSentryPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:Describe*'
                  - 'ec2:CreateTags'
                Resource: '*'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

Outputs:
  LearnCDK:
    Description: 'Stop Writing Cloudformation.Infrastructure Is Code:Learn CDK'
    Value: 'https://www.udemy.com/course/aws-cloud-development-kit-from-beginner-to-professional/?referralCode=E15D7FB64E417C547579&couponCode=AWS_4U_MAY'
