AWSTemplateFormatVersion: '2010-09-09'

Description: Miztiik Automation to demonstrate simple lambda function.

Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    Default: prod
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
            - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: lambda-function-${EnvName}
      Description: LambdaFunction to run python code
      Runtime: python3.7
      Handler: index.handler
      Code:
        ZipFile: |
          import json
          import time
          def handler(event, context):
              print(f"Lambda Executed Successfully, Hurray!")
              # This process of writing puzzles takes lot of effort
              # I need some rest
              time.sleep(15)
              print(f"Event: {json.dumps(event)}")
              return "Hi, There! Welcome to Mystikal World"
      MemorySize: 128
      Timeout: 20
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Environment:
        Variables:
          ENV:
            Fn::Sub: ${EnvName}
          TZ: UTC
      Tags: 
        - 
          Key: Application
          Value: Miztiik-Automation
        - 
          Key: GithubRepo
          Value: "https://github.com/miztiik/cfn-challenges"
        - 
          Key: LearnCdk
          Value: "https://www.udemy.com/course/aws-cloud-development-kit-from-beginner-to-professional"
        - 
          Key: Owner
          Value: Mystique
        - 
          Key: OwnerProfile
          Value: "https://github.com/miztiik"
        - 
          Key: ToKnowMore
          Value: "https://youtube.com/c/valaxytechnologies"

Outputs:
  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaRole
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaARN-${EnvName}