AWSTemplateFormatVersion: '2010-09-09'

Description: Miztiik Automation to demonstrate simple lambda function.

Parameters:
  EnvName:
    Type: String
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    Default: prod
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.

Resources:
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName:
        Fn::Sub: Miztiik-Automation-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: MiztiikAutomationPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - "s3:GetObjects"
                Resource: 
                  - "arn:aws:s3:::*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: lambda-function-${EnvName}
      Description: LambdaFunction to run python code
      Runtime: python3.8
      Handler: index.handler
      Code:
        ZipFile: |
          import json
          import time
          def handler(event, context):
              print(f"Lambda Executed Successfully, Hurray!")
              # This process of writing puzzles takes lot of effort
              # I need some rest
              time.sleep(15)
              print(f"Event: {json.dumps(event)}")
              return "Hi, There! Welcome to Mystikal World"
      MemorySize: 64
      Timeout: 1
      Role:
        Fn::GetAtt:
          - LambdaRole
          - Arn
      Environment:
        Variables:
          ENV:
            Fn::Sub: ${EnvName}
          TZ: UTC
      Tags: 
        - 
          Key: Application
          Value: Miztiik-Automation
        - 
          Key: GithubRepo
          Value: "https://github.com/miztiik/cfn-challenges"
        - 
          Key: LearnCdk
          Value: "https://www.udemy.com/course/aws-cloud-development-kit-from-beginner-to-professional/?referralCode=E15D7FB64E417C547579&couponCode=AWS_4U_MAY"
        - 
          Key: Owner
          Value: Mystique
        - 
          Key: OwnerProfile
          Value: "https://github.com/miztiik"
        - 
          Key: ToKnowMore
          Value: "https://youtube.com/c/valaxytechnologies"

Outputs:

  LearnCDK:
    Description: 'Stop Writing Cloudformation.Infrastructure Is Code:Learn CDK'
    Value: 'https://www.udemy.com/course/aws-cloud-development-kit-from-beginner-to-professional/?referralCode=E15D7FB64E417C547579&couponCode=AWS_4U_MAY'

  LambdaRoleARN:
    Description: Role for Lambda execution.
    Value:
      Fn::GetAtt:
        - LambdaRole
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaRole
  LambdaFunctionName:
    Value:
      Ref: LambdaFunction
  LambdaFunctionARN:
    Description: Lambda function ARN.
    Value:
      Fn::GetAtt:
        - LambdaFunction
        - Arn
    Export:
      Name:
        Fn::Sub: LambdaARN-${EnvName}